import type { CommandEffect, LinuxFoundation } from "./types";

/**
 * Command-level metadata used by the analyzer. Keep this beside the guide
 * catalog so adding a command does not require editing the UI or the parser.
 */
export const COMMAND_NAMES: Readonly<Record<string, string>> = {
  alias: "a shell shortcut manager",
  awk: "a text-processing language",
  base64: "a Base64 encoder and decoder",
  basename: "a filename extractor",
  blkid: "a block-device attribute viewer",
  cat: "a file reader",
  cd: "the shell's directory changer",
  chmod: "a permission mode changer",
  chown: "an ownership changer",
  chgrp: "a group ownership changer",
  chrt: "a real-time scheduling policy tool",
  clear: "the terminal display clearer",
  comm: "a sorted-file comparer",
  command: "the shell command resolver",
  cp: "a file copier",
  curl: "a network transfer client",
  cut: "a column selector",
  date: "a date and time formatter",
  dd: "a raw data copier",
  df: "a filesystem space reporter",
  diff: "a file difference reporter",
  docker: "the Docker command-line client",
  dirname: "a directory-name extractor",
  dmesg: "a kernel message viewer",
  depmod: "a kernel module dependency builder",
  du: "a directory space estimator",
  echo: "a text printer and file writer",
  env: "an environment viewer",
  export: "an environment variable exporter",
  exec: "a shell process replacer",
  file: "a file type detector",
  fdisk: "a partition-table editor",
  free: "a memory usage reporter",
  find: "a filesystem searcher",
  findfs: "a filesystem identifier resolver",
  findmnt: "a mounted-filesystem viewer",
  fstrim: "a filesystem discard tool",
  fsck: "a filesystem checker and repair tool",
  getconf: "a system-configuration viewer",
  getent: "a name-service database viewer",
  groups: "a group membership viewer",
  gzip: "a file compressor",
  grep: "a text searcher",
  head: "a file previewer",
  help: "the Bash builtin help viewer",
  history: "the shell history viewer",
  hostname: "a system name viewer",
  id: "a user and group identity viewer",
  install: "a file installer",
  ip: "the Linux network configuration tool",
  insmod: "a single kernel module loader",
  ionice: "an I/O scheduling policy tool",
  jobs: "the shell job viewer",
  join: "a sorted-file joiner",
  journalctl: "the system journal viewer",
  kill: "a process signal sender",
  last: "a login history viewer",
  less: "a paged file reader",
  ln: "a link creator",
  ls: "a directory lister",
  lsblk: "a block device lister",
  lscpu: "a CPU information viewer",
  lsmod: "a loaded-kernel-module viewer",
  lsns: "a Linux namespace viewer",
  logger: "a system-log message writer",
  man: "the local manual viewer",
  md5sum: "an MD5 checksum tool",
  mkdir: "a directory creator",
  mktemp: "a temporary file creator",
  modinfo: "a kernel module metadata viewer",
  modprobe: "a kernel module loader",
  mount: "a filesystem mounter",
  mv: "a file mover and renamer",
  nice: "a process priority wrapper",
  nl: "a line numberer",
  nohup: "a hangup-resistant command wrapper",
  nsenter: "a namespace entry tool",
  od: "a byte representation viewer",
  passwd: "a password manager",
  paste: "a column joiner",
  pacman: "the Arch Linux package manager",
  pgrep: "a process finder",
  pkill: "a process signal matcher",
  popd: "a directory stack popper",
  printenv: "an environment variable viewer",
  printf: "a formatted text printer",
  ps: "a process list viewer",
  pwd: "the current directory viewer",
  pushd: "a directory stack pusher",
  read: "a shell input reader",
  readlink: "a symbolic link reader",
  realpath: "a canonical path resolver",
  rm: "a file remover",
  rmdir: "an empty directory remover",
  renice: "a process priority changer",
  rsync: "a file synchronization tool",
  rmmod: "a kernel module remover",
  scp: "an SSH file copier",
  sed: "a stream text editor",
  seq: "a number sequence generator",
  sha256sum: "a SHA-256 checksum tool",
  shred: "a file overwrite tool",
  shuf: "a random line selector",
  sleep: "a delay command",
  split: "a file splitter",
  ss: "a socket viewer",
  sort: "a line sorter",
  source: "a shell file loader",
  stat: "a file metadata viewer",
  stty: "a terminal setting manager",
  su: "a user switcher",
  swapoff: "a swap deactivator",
  swapon: "a swap activator",
  sysctl: "a kernel runtime-parameter viewer",
  systemctl: "the systemd service manager",
  taskset: "a process CPU-affinity tool",
  tail: "a file ending previewer",
  tar: "an archive manager",
  tac: "a reverse line printer",
  tee: "a pipeline output splitter",
  test: "a shell condition tester",
  top: "a live process viewer",
  touch: "a file creator",
  tr: "a character translator",
  truncate: "a file size changer",
  type: "the shell command resolver",
  umask: "a new-file permission mask manager",
  umount: "a filesystem unmount tool",
  unshare: "a namespace creation tool",
  udevadm: "the Linux device-manager control tool",
  unalias: "a shell alias remover",
  uniq: "an adjacent duplicate filter",
  uname: "a system identity viewer",
  unset: "a shell variable remover",
  uptime: "a system uptime viewer",
  wget: "a web downloader",
  wc: "a file counter",
  which: "an executable locator",
  whoami: "the current user viewer",
  who: "a logged-in user viewer",
  xargs: "a command builder",
  yes: "a repeated output generator",
  partx: "a kernel partition-table updater",
  prlimit: "a process resource-limit tool",
  setpriv: "a process privilege configuration tool",
};

export const DIRECT_GUIDES: Readonly<Record<string, string>> = {
  alias: "alias",
  cat: "cat",
  clear: "clear",
  env: "env",
  export: "export",
  history: "history",
  ls: "ls",
  mkdir: "mkdir",
  mv: "mv",
  ps: "ps",
  pwd: "pwd",
  rm: "rm",
  sort: "sort",
  top: "top",
  touch: "touch",
  type: "type",
  uname: "uname",
  wc: "wc",
  which: "which",
  whoami: "whoami",
};

export const MUTATING_GUIDES: ReadonlySet<string> = new Set([
  "alias", "chrt", "chgrp", "chmod", "chown", "cp", "echo", "export", "gzip", "install", "ln", "mkdir", "mktemp",
  "mount", "depmod", "fstrim", "fdisk", "insmod", "ionice", "logger", "modprobe", "mv", "nsenter", "passwd",
  "pacmanInstall", "pacmanRemove", "pacmanSyu", "pacmanUpgrade", "popd", "pushd", "rm", "rmdir", "renice", "rmmod",
  "sed", "setpriv", "set", "stty", "swapoff", "swapon", "sync", "sysctl", "taskset", "tee", "tarCreate", "touch",
  "truncate", "umask", "umount", "unalias", "unset", "udevadm", "unshare", "partx", "prlimit", "systemctlDaemonReload",
  "systemctlDisable", "systemctlEnable", "systemctlRestart", "systemctlStart", "systemctlStop", "tarAppend", "tarDelete",
  "tarExtract", "tarUpdate",
]);

export const DANGEROUS_GUIDES: ReadonlySet<string> = new Set([
  "chrt", "dd", "exec", "fdisk", "fsck", "fstrim", "insmod", "kill", "modprobe", "mount", "nsenter", "partx",
  "passwd", "pacmanRemove", "pacmanUpgrade", "pkill", "prlimit", "rm", "rmmod", "setpriv", "shred", "source", "swapoff",
  "sysctl", "systemctlDisable", "systemctlRestart", "systemctlStart", "systemctlStop", "tarDelete", "tarExtract", "taskset",
  "truncate", "udevadm", "umount", "unshare",
]);

export const EXTERNAL_GUIDES: ReadonlySet<string> = new Set(["curl", "rsync", "scp", "ssh", "wget", "xargs"]);

export const ARGUMENT_MEANINGS: Readonly<Record<string, string>> = {
  alias: "the name and shortcut to save in this shell",
  awk: "the program and input fields to process",
  basename: "the path and optional suffix to strip",
  blkid: "the block device whose filesystem tags should be printed",
  chgrp: "the new group and path to change",
  chrt: "the scheduling policy, priority, or process ID to inspect",
  cd: "the directory where the shell should move",
  chmod: "the permission mode and path to change",
  chown: "the new user, group, and path",
  comm: "the two sorted files to compare",
  cp: "the source path and destination path",
  curl: "the URL and optional request data",
  cut: "the fields, characters, or bytes to select",
  dirname: "the path whose directory name should be printed",
  diff: "the two files or directories to compare",
  depmod: "the kernel release whose module dependencies should be generated",
  file: "the path to identify",
  fdisk: "the block device whose partition table should be inspected",
  findType: "the starting path and entry type to keep",
  findName: "the starting path and search pattern",
  findfs: "the label, UUID, or partition tag to resolve",
  findmnt: "the device or mountpoint to inspect",
  fstrim: "the mounted filesystem whose unused blocks should be discarded",
  fsck: "the filesystem to check",
  getconf: "the configuration variable and optional pathname to query",
  getent: "the NSS database and optional key to query",
  grep: "the pattern and file whose contents will be read",
  groups: "the user whose group membership should be printed",
  hostname: "the name or hostname information to inspect",
  id: "the user whose identity should be printed",
  install: "the source file and destination path",
  insmod: "the kernel module file to insert",
  ip: "the network object and address or route arguments",
  ionice: "the process ID or command whose I/O priority should change",
  jobs: "the shell job identifier to inspect",
  echo: "the text to print or write",
  last: "the user or terminal whose login records should be shown",
  head: "the line count and file to read",
  journalctlBoot: "the boot filter to inspect",
  kill: "the process ID that receives the signal",
  less: "the file to read",
  ln: "the target and new link name",
  man: "the command whose manual page will open",
  mkdir: "the directory to create",
  mktemp: "the filename template or temporary directory",
  modinfo: "the kernel module whose metadata should be printed",
  modprobe: "the kernel module to load or remove",
  mount: "the device and directory to connect",
  mv: "the source path and new path",
  nice: "the command whose scheduling priority should change",
  nl: "the file whose lines should be numbered",
  nohup: "the command that should survive terminal hangup",
  nsenter: "the target process ID and namespaces to enter",
  passwd: "the account whose password status should change",
  paste: "the files whose lines should be joined",
  pacmanInstall: "the package to install",
  pacmanQueryInfo: "the installed package to inspect",
  pacmanQuerySearch: "the term to search among installed packages",
  pacmanRemove: "the package to remove",
  pacmanSearchRepo: "the term to search in repositories",
  pgrep: "the process name or pattern to find",
  pkill: "the process pattern that receives the signal",
  printf: "the format string and values to print",
  printenv: "the environment variable to read",
  pushd: "the directory to push onto the shell stack",
  read: "the shell variables that receive input",
  readlink: "the symbolic link or path to resolve",
  realpath: "the path to canonicalize",
  renice: "the process, process group, or user whose priority should change",
  rm: "the path to remove",
  rmdir: "the empty directory to remove",
  rmmod: "the kernel module to remove",
  rsync: "the source and destination paths to synchronize",
  scp: "the local or remote source and destination paths",
  sed: "the editing script and input file",
  seq: "the first, increment, and last numbers",
  setpriv: "the program whose privilege context should change",
  shred: "the file to overwrite or remove",
  split: "the input file and output prefix",
  ss: "the socket filters to inspect",
  sort: "the file whose lines will be sorted",
  source: "the shell file to read and execute",
  stat: "the path whose metadata should be printed",
  su: "the account and optional command to run as that user",
  swapoff: "the swap device or file to disable",
  swapon: "the swap device or file to enable",
  sysctl: "the kernel parameter or configuration file to inspect",
  systemctlStatus: "the service to inspect",
  systemctlStart: "the service to start",
  systemctlStop: "the service to stop",
  systemctlRestart: "the service to restart",
  systemctlEnable: "the service to enable at startup",
  systemctlDisable: "the service to disable at startup",
  taskset: "the CPU mask or process whose affinity should change",
  tac: "the input file whose records should be reversed",
  tail: "the line count and file to read",
  tarCreate: "the archive name and files to store in it",
  tar: "the archive operation and its archive filename",
  tarAppend: "the archive name and files to append",
  tarDelete: "the uncompressed archive and members to remove",
  tarDiff: "the archive and filesystem members to compare",
  tarExtract: "the archive and optional members to extract",
  tarList: "the archive name to inspect",
  tarUpdate: "the archive name and files to update",
  tee: "the output files that should receive a copy",
  test: "the file, string, or numeric condition to evaluate",
  touch: "the file to create or timestamp to update",
  tr: "the character sets to translate or delete",
  truncate: "the file and target size to apply",
  type: "the command name to resolve",
  umask: "the permission mask to show or set",
  umount: "the device or directory to detach",
  unshare: "the namespaces and program to isolate",
  udevadm: "the device path or udev subcommand to inspect",
  uniq: "the input whose adjacent duplicates should be filtered",
  unset: "the variable or function name to remove",
  uptime: "the uptime format or display mode",
  wget: "the URL and download destination",
  wc: "the file to measure",
  which: "the executable name to locate",
  who: "the login record or output mode to inspect",
  xargs: "the input items and command to construct",
  partx: "the block device and partition numbers to update",
  prlimit: "the process and resource limits to inspect or set",
};

export const FOUNDATION_BY_COMMAND: Readonly<Record<string, readonly LinuxFoundation[]>> = {
  alias: ["shell"], awk: ["text"], cat: ["filesystem", "text"], cd: ["shell", "filesystem"], chmod: ["filesystem", "system"],
  chown: ["filesystem", "system"], comm: ["text"], cp: ["filesystem"], curl: ["network"], df: ["filesystem"], diff: ["filesystem", "text"],
  du: ["filesystem"], echo: ["shell", "text"], env: ["shell"], export: ["shell"], find: ["filesystem"], free: ["system"],
  grep: ["filesystem", "text"], head: ["text"], ip: ["network", "system"], journalctl: ["system", "text"], kill: ["processes"],
  less: ["filesystem", "text"], ls: ["filesystem"], mkdir: ["filesystem"], mount: ["filesystem", "system"], mv: ["filesystem"],
  pacman: ["packages", "system"], ping: ["network"], ps: ["processes"], pwd: ["shell", "filesystem"], rm: ["filesystem"],
  sed: ["filesystem", "text"], sort: ["text"], ssh: ["network", "system"], systemctl: ["system", "processes"], tail: ["text"],
  tar: ["filesystem"], tee: ["filesystem", "text"], touch: ["filesystem"], tr: ["text"], uname: ["system"], uniq: ["text"],
  wc: ["filesystem", "text"], wget: ["network"],
};

export const EFFECTS_BY_COMMAND: Readonly<Record<string, readonly CommandEffect[]>> = {
  alias: ["shell"], cd: ["shell"], chmod: ["filesystem"], chown: ["filesystem"], cp: ["filesystem"], curl: ["network"],
  echo: ["shell"], export: ["shell"], find: ["filesystem"], grep: ["filesystem"], ip: ["network"], kill: ["processes"],
  mkdir: ["filesystem"], mount: ["filesystem"], mv: ["filesystem"], pacman: ["packages"], ping: ["network"], ps: ["processes"],
  rm: ["filesystem"], sed: ["filesystem"], ssh: ["network"], systemctl: ["processes"], tar: ["filesystem"], tee: ["filesystem"],
  touch: ["filesystem"], wget: ["network"],
};

export const PRIVILEGE_COMMANDS: ReadonlySet<string> = new Set(["sudo", "su", "doas", "setpriv", "passwd"]);
