import type { CommandCatalog } from "../types";
import type { ManPage } from "../../manpage-matcher";

/** ArchWiki sources used for the command coverage manifest. */
export const ARCHWIKI_SOURCES = [
  { name: "Commands", url: "https://wiki.archlinux.org/title/Category%3ACommands", retrievedAt: "2026-09-27" },
  { name: "Core utilities", url: "https://wiki.archlinux.org/title/Core_utilities", retrievedAt: "2026-09-27" },
] as const;

/** Normalized executable names from ArchWiki Category:Commands. */
export const ARCHWIKI_CATEGORY_COMMANDS = [
  "acme.sh",
  "adb",
  "arch-chroot",
  "at",
  "awk",
  "badblocks",
  "bluetoothctl",
  "certbot",
  "chattr",
  "chmod",
  "chown",
  "chroot",
  "chsh",
  "crontab",
  "dd",
  "dhcpcd",
  "diff",
  "dig",
  "dmesg",
  "doas",
  "drill",
  "fdisk",
  "ffmpeg",
  "find",
  "fsck",
  "fzf",
  "git",
  "gm",
  "gpg",
  "gdisk",
  "cgdisk",
  "sgdisk",
  "grep",
  "gs",
  "hwclock",
  "info",
  "ip",
  "journalctl",
  "jj",
  "loadkeys",
  "locale-gen",
  "localectl",
  "lp",
  "ls",
  "lsblk",
  "makepkg",
  "man",
  "mkinitcpio",
  "modinfo",
  "modprobe",
  "mount",
  "namcap",
  "nc",
  "netcat",
  "netctl",
  "openssl",
  "pacman-key",
  "pactree",
  "parted",
  "ping",
  "pkgfile",
  "rad",
  "rsync",
  "sed",
  "setcap",
  "setfattr",
  "setkeycodes",
  "sftp",
  "showkey",
  "shred",
  "ss",
  "ssh-keygen",
  "su",
  "sudo",
  "sudoedit",
  "sysctl",
  "systemctl",
  "run0",
  "tar",
  "telnet",
  "tex",
  "timedatectl",
  "traceroute",
  "umask",
  "umount",
  "useradd",
  "wg",
  "whois",
  "xdg-open",
] as const;

/** Executable names listed by the Core utilities tables. */
export const CORE_UTILITY_COMMANDS = [
  "cd",
  "ls",
  "cat",
  "mkdir",
  "rmdir",
  "rm",
  "cp",
  "mv",
  "ln",
  "chown",
  "chmod",
  "dd",
  "df",
  "du",
  "tar",
  "less",
  "find",
  "diff",
  "grep",
  "sed",
  "awk",
  "dmesg",
  "lsblk",
  "mount",
  "umount",
  "su",
  "kill",
  "pgrep",
  "ps",
  "free",
  "alias",
  "type",
  "time",
  "tee",
  "mktemp",
  "mknod",
  "wc",
  "strings",
  "column",
  "xargs",
  "iconv",
  "uudecode",
  "file",
] as const;

const ARCHWIKI_GUIDE_ALIASES: Readonly<Record<string, readonly string[]>> = {
  find: ["findName","findType"],
  tar: ["tarCreate","tarList","tarExtract","tarAppend","tarUpdate","tarDiff","tarDelete"],
  systemctl: ["systemctlFailed","systemctlStatus","systemctlStart","systemctlStop","systemctlRestart","systemctlEnable","systemctlDisable","systemctlDaemonReload"],
  journalctl: ["journalctlBoot"],
};

export function missingArchWikiCommands(catalog: Readonly<Record<string, ManPage>>): readonly string[] {
  const commands = [...new Set([...ARCHWIKI_CATEGORY_COMMANDS, ...CORE_UTILITY_COMMANDS])];
  return commands.filter((command) => !catalog[command] && !(ARCHWIKI_GUIDE_ALIASES[command] ?? []).some((guideId) => catalog[guideId]));
}

function generatedGuide(command: string, purpose: string): ManPage {
  return {
    purpose,
    syntax: `${command} [options] [arguments]`,
    parts: [],
    note: "Generated coverage entry from ArchWiki. Read the local man page or --help before relying on command-specific options.",
  };
}

export const archwikiGuides = {
  "acme.sh": generatedGuide("acme.sh", "Issue and renew TLS certificates with the ACME protocol."),
  adb: generatedGuide("adb", "Control Android devices from the command line."),
  "arch-chroot": generatedGuide("arch-chroot", "Enter a mounted Arch Linux installation as a chroot environment."),
  at: generatedGuide("at", "Schedule a command to run once at a later time."),
  badblocks: generatedGuide("badblocks", "Search a block device for bad sectors."),
  bluetoothctl: generatedGuide("bluetoothctl", "Inspect and control Bluetooth devices."),
  certbot: generatedGuide("certbot", "Obtain and manage certificates with Let's Encrypt."),
  chattr: generatedGuide("chattr", "Change extended attributes on a filesystem path."),
  chroot: generatedGuide("chroot", "Run a command with a different root directory."),
  chsh: generatedGuide("chsh", "Change a user's login shell."),
  crontab: generatedGuide("crontab", "Install or edit a user's scheduled cron jobs."),
  dhcpcd: generatedGuide("dhcpcd", "Configure network interfaces with DHCP."),
  dig: generatedGuide("dig", "Query DNS records and inspect name resolution."),
  doas: generatedGuide("doas", "Run a command with another user's privileges."),
  drill: generatedGuide("drill", "Query DNS records."),
  ffmpeg: generatedGuide("ffmpeg", "Convert, record, and process audio or video."),
  fzf: generatedGuide("fzf", "Interactively filter and select text."),
  git: generatedGuide("git", "Track changes and collaborate on source code."),
  gm: generatedGuide("gm", "Process images with GraphicsMagick."),
  gpg: generatedGuide("gpg", "Encrypt, sign, and verify data with OpenPGP."),
  gdisk: generatedGuide("gdisk", "Edit a GPT partition table."),
  cgdisk: generatedGuide("cgdisk", "Edit a GPT partition table with a curses interface."),
  sgdisk: generatedGuide("sgdisk", "Manage GPT partition tables from scripts."),
  gs: generatedGuide("gs", "Interpret and convert PostScript and PDF documents."),
  hwclock: generatedGuide("hwclock", "Read or set the hardware clock."),
  info: generatedGuide("info", "Read GNU Info documentation."),
  jj: generatedGuide("jj", "Manage versioned files with the Jujutsu version-control system."),
  loadkeys: generatedGuide("loadkeys", "Load keyboard mappings for the Linux console."),
  "locale-gen": generatedGuide("locale-gen", "Generate locale data installed on the system."),
  localectl: generatedGuide("localectl", "Inspect or change system locale and keyboard settings."),
  lp: generatedGuide("lp", "Submit a file to a print queue."),
  makepkg: generatedGuide("makepkg", "Build Arch Linux packages from a PKGBUILD."),
  mkinitcpio: generatedGuide("mkinitcpio", "Create an initial RAM filesystem for Linux."),
  namcap: generatedGuide("namcap", "Check Arch Linux packages and PKGBUILDs for common problems."),
  nc: generatedGuide("nc", "Read and write data across network connections."),
  netcat: generatedGuide("netcat", "Read and write data across network connections."),
  netctl: generatedGuide("netctl", "Manage network profiles on Arch Linux."),
  openssl: generatedGuide("openssl", "Use TLS and cryptographic primitives from the command line."),
  "pacman-key": generatedGuide("pacman-key", "Manage the pacman package signing keyring."),
  pactree: generatedGuide("pactree", "Display dependency trees for Arch Linux packages."),
  parted: generatedGuide("parted", "Create and edit partition tables."),
  pkgfile: generatedGuide("pkgfile", "Search which Arch Linux package contains a file."),
  rad: generatedGuide("rad", "Use the Radicle distributed collaboration tools."),
  rsync: generatedGuide("rsync", "Synchronize files and directories between locations."),
  setcap: generatedGuide("setcap", "Set file capabilities."),
  setfattr: generatedGuide("setfattr", "Set extended filesystem attributes."),
  setkeycodes: generatedGuide("setkeycodes", "Map keyboard scan codes to key codes."),
  sftp: generatedGuide("sftp", "Transfer files through an SSH connection."),
  showkey: generatedGuide("showkey", "Inspect keyboard codes from the Linux console."),
  "ssh-keygen": generatedGuide("ssh-keygen", "Create and manage SSH authentication keys."),
  sudo: generatedGuide("sudo", "Run a command with administrator privileges."),
  sudoedit: generatedGuide("sudoedit", "Edit a file through sudo using a user's editor."),
  run0: generatedGuide("run0", "Run a command through systemd with a transient privilege boundary."),
  telnet: generatedGuide("telnet", "Connect to a remote host using the Telnet protocol."),
  tex: generatedGuide("tex", "Typeset documents with the TeX system."),
  timedatectl: generatedGuide("timedatectl", "Inspect or change system date and time settings."),
  traceroute: generatedGuide("traceroute", "Trace the network path to a destination."),
  useradd: generatedGuide("useradd", "Create a user account."),
  wg: generatedGuide("wg", "Configure WireGuard interfaces."),
  whois: generatedGuide("whois", "Query domain registration information."),
  "xdg-open": generatedGuide("xdg-open", "Open a path or URL with the desktop's preferred application."),
  time: generatedGuide("time", "Measure how long a command takes to run."),
  mknod: generatedGuide("mknod", "Create a filesystem node such as a device or FIFO."),
  strings: generatedGuide("strings", "Print readable character sequences from binary data."),
  column: generatedGuide("column", "Format text into aligned columns."),
  iconv: generatedGuide("iconv", "Convert text between character encodings."),
  uudecode: generatedGuide("uudecode", "Decode files encoded for transport in email or text."),
} satisfies CommandCatalog;
