import type { CommandCatalog } from "../types";
export const filesystemGuides = {
  ls: {
    purpose: "List the files and directories in a path.",
    syntax: "ls [options] [path]",
    parts: [
      { token: "-l", meaning: "Use the long format with permissions, owner, size, and date." },
      { token: "-a", meaning: "Include hidden entries whose names start with a dot." },
      { token: "-h", meaning: "Show sizes in a human-readable format when used with -l." },
      { token: "-la", meaning: "Combine -l and -a. This is the form used in the exercise." },
    ],
    note: "Options can often be combined. Read ls -la from left to right as long format plus all entries.",
  },
  cat: {
    purpose: "Print a short file directly to standard output.",
    syntax: "cat [file]",
    parts: [],
    note: "Use cat for short files. Use less when the output may be longer than one screen.",
  },
  less: {
    purpose: "Read a file one screen at a time.",
    syntax: "less [file]",
    parts: [
      { token: "Space", meaning: "Move forward one screen in a real less session." },
      { token: "q", meaning: "Quit the pager in a real terminal." },
    ],
    note: "The practice shell prints the file as a safe preview. The real less program is interactive.",
  },
  mkdir: {
    purpose: "Create one or more directories.",
    syntax: "mkdir [options] directory",
    parts: [
      { token: "-p", meaning: "Create missing parent directories and avoid an error when the target exists." },
    ],
    note: "The exercise uses the plain form because the parent directory already exists.",
  },
  touch: {
    purpose: "Create an empty file or update a file's timestamps.",
    syntax: "touch file",
    parts: [],
    note: "touch does not open an editor. Use echo, a text editor, or a redirect to add content.",
  },
  cp: {
    purpose: "Copy a file or directory to another path.",
    syntax: "cp [options] source destination",
    parts: [
      { token: "-r", meaning: "Copy a directory and its contents recursively." },
    ],
    note: "cp keeps the original. Check the destination path before copying over an existing file.",
  },
  mv: {
    purpose: "Move a path or rename it.",
    syntax: "mv source destination",
    parts: [],
    note: "mv does not keep a second copy. A rename stays on the same filesystem when possible.",
  },
  rm: {
    purpose: "Remove a file or, with care, a directory tree.",
    syntax: "rm [options] path",
    parts: [
      { token: "-r", meaning: "Remove a directory and its contents recursively." },
      { token: "-f", meaning: "Skip some prompts and missing-file errors in a real shell." },
    ],
    note: "rm has no recycle bin. Confirm the path and use the smallest option set that solves the task.",
  },
  findName: {
    purpose: "Search a directory tree for paths whose names match a pattern.",
    syntax: "find path -name pattern",
    parts: [
      { token: "-name", meaning: "Match the final name of each path." },
      { token: ".", meaning: "Start at the current directory." },
    ],
    note: "Quote patterns containing wildcards so the shell does not expand them before find sees them.",
  },
  findType: {
    purpose: "Search a directory tree and keep only one kind of filesystem entry.",
    syntax: "find path -type f",
    parts: [
      { token: "-type f", meaning: "Keep regular files." },
      { token: "-type d", meaning: "Keep directories instead." },
      { token: "-print0", meaning: "Print each matching path separated by a NUL byte, which is safe for unusual filenames." },
    ],
    note: "Combine -type with -name when a search needs both a kind and a name.",
  },
  lsLong: {
    purpose: "Inspect permissions, ownership, size, and timestamp for one path.",
    syntax: "ls -l path",
    parts: [
      { token: "-l", meaning: "Use the long listing format." },
      { token: "rwx", meaning: "Read, write, and execute permission bits." },
    ],
    note: "Read the mode as owner, group, then others. The first character tells you file or directory.",
  },
  chmod: {
    purpose: "Change the permission mode of a path.",
    syntax: "chmod 600 file",
    parts: [
      { token: "6", meaning: "Owner gets read 4 plus write 2." },
      { token: "0", meaning: "The group gets no permissions." },
      { token: "0", meaning: "Other users get no permissions." },
    ],
    note: "The three digits represent owner, group, and others. Read 4, write 2, and execute 1 are added together.",
  },
  chown: {
    purpose: "Change the owner and group recorded for a path.",
    syntax: "chown user:group file",
    parts: [
      { token: ":", meaning: "Separate the new user name from the new group name." },
    ],
    note: "Changing ownership usually needs administrator privileges on a real system.",
  },
  chgrp: {
    purpose: "Change the group ownership recorded for a file or directory.",
    syntax: "chgrp [options] group path",
    parts: [
      { token: "-R", meaning: "Apply the group change recursively to a directory tree." },
      { token: "-h", meaning: "Change a symbolic link itself instead of its target." },
      { token: "--reference", meaning: "Copy the group from another reference path." },
    ],
    note: "Changing group ownership may require administrator privileges and affects access checks.",
  },
  basename: {
    purpose: "Remove the directory part from a path and print the remaining filename.",
    syntax: "basename [options] path [suffix]",
    parts: [
      { token: "-a", meaning: "Process every path argument instead of only the first." },
      { token: "-s", meaning: "Remove the chosen suffix from the result." },
      { token: "-z", meaning: "End each result with a NUL byte instead of a newline." },
    ],
    note: "basename extracts a name. It does not check whether the path exists.",
  },
  dirname: {
    purpose: "Remove the final filename component from a path and print its directory.",
    syntax: "dirname [options] path",
    parts: [
      { token: "-z", meaning: "End the result with a NUL byte instead of a newline." },
    ],
    note: "dirname works on the text of a path. It does not need the path to exist.",
  },
  file: {
    purpose: "Identify the type of a file from its contents and metadata.",
    syntax: "file [options] path",
    parts: [
      { token: "-b", meaning: "Print the file type without the filename." },
      { token: "-i", meaning: "Print a MIME type and character encoding." },
      { token: "-L", meaning: "Follow symbolic links and inspect their targets." },
      { token: "-z", meaning: "Inspect the contents of compressed files." },
    ],
    note: "file detects formats. It does not open a file in an editor or guarantee that a file is safe.",
  },
  ln: {
    purpose: "Create a hard link or symbolic link to a file or directory.",
    syntax: "ln [options] target link-name",
    parts: [
      { token: "-s", meaning: "Create a symbolic link instead of a hard link." },
      { token: "-f", meaning: "Remove an existing destination before creating the link." },
      { token: "-i", meaning: "Ask before replacing an existing destination." },
      { token: "-n", meaning: "Treat a symlink to a directory as a normal destination." },
      { token: "-v", meaning: "Print each link as it is created." },
    ],
    note: "A symbolic link stores a path. A hard link points to the same filesystem data and usually cannot cross filesystems.",
  },
  readlink: {
    purpose: "Print the target stored in a symbolic link or resolve a path.",
    syntax: "readlink [options] path",
    parts: [
      { token: "-f", meaning: "Resolve every symlink and make the final path absolute." },
      { token: "-e", meaning: "Resolve links only when every part of the path exists." },
      { token: "-m", meaning: "Resolve links without requiring the path to exist." },
      { token: "-n", meaning: "Do not print the final newline." },
    ],
    note: "readlink reads link metadata. It does not follow a link and execute what it points to.",
  },
  realpath: {
    purpose: "Print a canonical absolute path with symbolic links and dot segments resolved.",
    syntax: "realpath [options] path",
    parts: [
      { token: "-e", meaning: "Require every part of the path to exist." },
      { token: "-m", meaning: "Allow missing path components while resolving the name." },
      { token: "-L", meaning: "Follow logical links before resolving dot segments." },
      { token: "-P", meaning: "Resolve physical links before resolving dot segments." },
    ],
    note: "realpath normalizes names. It does not create directories or files.",
  },
  rmdir: {
    purpose: "Remove empty directories.",
    syntax: "rmdir [options] directory",
    parts: [
      { token: "-p", meaning: "Remove empty parent directories after the target." },
      { token: "-v", meaning: "Print a message for each directory removed." },
      { token: "--ignore-fail-on-non-empty", meaning: "Ignore a failure caused by a non-empty directory." },
    ],
    note: "rmdir refuses non-empty directories. Use rm -r only when you have checked the complete tree.",
  },
  du: {
    purpose: "Estimate how much disk space files and directories use.",
    syntax: "du [options] [path]",
    parts: [
      { token: "-h", meaning: "Use readable units such as KiB, MiB, and GiB." },
      { token: "-s", meaning: "Print one total for each argument instead of every child." },
      { token: "-a", meaning: "Include files as well as directories." },
      { token: "-d", meaning: "Limit how many directory levels are reported." },
      { token: "-x", meaning: "Stay on the same filesystem." },
    ],
    note: "du measures directory contents. df measures free space on mounted filesystems.",
  },
  df: {
    purpose: "Report free and used space on mounted filesystems.",
    syntax: "df [options] [path]",
    parts: [
      { token: "-h", meaning: "Use readable units such as GiB and MiB." },
      { token: "-T", meaning: "Include the filesystem type." },
      { token: "-i", meaning: "Report inode usage instead of block usage." },
      { token: "-a", meaning: "Include pseudo, duplicate, and inaccessible filesystems." },
      { token: "-x", meaning: "Exclude a filesystem type from the report." },
    ],
    note: "df answers whether a filesystem is full. Check both space and inodes when writes fail unexpectedly.",
  },
  stat: {
    purpose: "Print detailed metadata about a file or filesystem.",
    syntax: "stat [options] path",
    parts: [
      { token: "-c", meaning: "Print metadata using a custom format." },
      { token: "--printf", meaning: "Print metadata using a format string without adding a final newline automatically." },
      { token: "-f", meaning: "Report the filesystem instead of the file." },
      { token: "-L", meaning: "Follow symbolic links." },
      { token: "-t", meaning: "Print compact machine-readable output." },
    ],
    note: "stat can reveal permissions, ownership, size, timestamps, and inode information.",
  },
  install: {
    purpose: "Copy a file while setting its permissions, owner, or destination directory.",
    syntax: "install [options] source destination",
    parts: [
      { token: "-D", meaning: "Create missing parent directories before copying." },
      { token: "-m", meaning: "Set the destination permission mode." },
      { token: "-o", meaning: "Set the destination owner." },
      { token: "-g", meaning: "Set the destination group." },
      { token: "-s", meaning: "Strip symbols from an installed executable." },
      { token: "-v", meaning: "Print each installation action." },
    ],
    note: "install is common in package and build scripts. It can create directories and change ownership.",
  },
  mktemp: {
    purpose: "Create a unique temporary file or directory.",
    syntax: "mktemp [options] template",
    parts: [
      { token: "-d", meaning: "Create a directory instead of a file." },
      { token: "-p", meaning: "Create the item inside a chosen temporary directory." },
      { token: "--suffix", meaning: "Append a chosen suffix after the random part." },
      { token: "-u", meaning: "Print a name without creating it. This can create race conditions." },
    ],
    note: "Prefer mktemp over guessing a temporary filename. Do not use -u when another process could create the same name.",
  },
  shred: {
    purpose: "Overwrite a file to make ordinary recovery harder before removing it.",
    syntax: "shred [options] file",
    parts: [
      { token: "-n", meaning: "Overwrite the file this many times." },
      { token: "-z", meaning: "Add a final zero-filled overwrite." },
      { token: "-u", meaning: "Remove the file after overwriting it." },
      { token: "-v", meaning: "Print progress information." },
    ],
    note: "shred is not reliable on copy-on-write, journaling, compressed, or flash filesystems. Encryption is a stronger design choice.",
  },
  truncate: {
    purpose: "Change a file to a chosen size, usually by removing or adding zero bytes.",
    syntax: "truncate [options] file",
    parts: [
      { token: "-s", meaning: "Set the new size, such as 0, +1K, or -1M." },
      { token: "--no-create", meaning: "Do not create the file when it does not exist." },
      { token: "--reference", meaning: "Use another file's size as the target size." },
    ],
    note: "truncate can destroy file contents immediately when the new size is smaller.",
  },
  dd: {
    purpose: "Copy and transform raw data at the byte level.",
    syntax: "dd [options]",
    parts: [
      { token: "if=", meaning: "Read from this input file instead of standard input." },
      { token: "of=", meaning: "Write to this output file instead of standard output." },
      { token: "bs=", meaning: "Use this input and output block size." },
      { token: "count=", meaning: "Copy only this many blocks." },
      { token: "status=progress", meaning: "Show transfer progress while copying." },
      { token: "conv=", meaning: "Apply a conversion such as sync, noerror, or notrunc." },
    ],
    note: "dd can overwrite disks and partitions without a recycle bin. Recheck if= and of= before running it.",
  },
  mount: {
    purpose: "Attach a filesystem to a directory in the filesystem tree, or list mounted filesystems.",
    syntax: "mount [options] device directory",
    parts: [
      { token: "-t", meaning: "Choose the filesystem type." },
      { token: "-o", meaning: "Set mount options such as ro, noexec, or uid." },
      { token: "-a", meaning: "Mount all filesystems listed in the configuration." },
      { token: "-r", meaning: "Mount read-only." },
      { token: "-w", meaning: "Mount read-write when supported." },
    ],
    note: "mount changes system state and commonly needs root. Verify the device and directory before using it.",
  },
  umount: {
    purpose: "Detach a mounted filesystem from the filesystem tree.",
    syntax: "umount [options] device-or-directory",
    parts: [
      { token: "-a", meaning: "Unmount all eligible filesystems." },
      { token: "-l", meaning: "Detach now and clean up references when the filesystem is no longer busy." },
      { token: "-R", meaning: "Recursively unmount a target and its nested mounts." },
      { token: "-f", meaning: "Force an unmount where the filesystem supports it." },
    ],
    note: "Unmounting a busy filesystem can interrupt programs. Check open files and active shells first.",
  },
  findmnt: {
    purpose: "List, search, and verify mounted filesystems and mount-table entries.",
    syntax: "findmnt [options] [device|mountpoint]",
    parts: [
      { token: "-A", meaning: "Disable built-in filters and show all filesystems." },
      { token: "-a", meaning: "Use ASCII characters instead of tree-drawing characters." },
      { token: "-b", meaning: "Print sizes in bytes." },
      { token: "-C", meaning: "Do not canonicalize paths while comparing them." },
      { token: "-c", meaning: "Canonicalize paths." },
      { token: "-D", meaning: "Imitate df output and omit pseudo-filesystems." },
      { token: "-J", meaning: "Print JSON output." },
      { token: "-n", meaning: "Hide the column headings." },
      { token: "-o", meaning: "Choose the output columns." },
      { token: "-t", meaning: "Filter by filesystem type." },
      { token: "--verify", meaning: "Check whether the mount table is internally correct." },
      { token: "-p", meaning: "Poll the mount table and report changes." },
      { token: "-x", meaning: "Verify the mount table content." },
    ],
    note: "For scripts, choose explicit output columns with -o and prefer JSON when the consumer supports it.",
  },
  blkid: {
    purpose: "Locate block devices and print filesystem labels, UUIDs, and types.",
    syntax: "blkid [options] [device]",
    parts: [
      { token: "-o", meaning: "Choose the output format, such as value or export." },
      { token: "-s", meaning: "Print only the selected tag." },
      { token: "-p", meaning: "Perform a low-level probing operation." },
      { token: "-c", meaning: "Use a chosen cache file, or /dev/null to bypass the cache." },
      { token: "-d", meaning: "Do not encode non-printing characters in values." },
      { token: "-D", meaning: "Do not print partition-table details." },
      { token: "-i", meaning: "Gather I/O limit information." },
      { token: "-k", meaning: "List known filesystem and RAID types." },
      { token: "-l", meaning: "Return only the first device matching a token." },
      { token: "-L", meaning: "Find the device with a given filesystem label." },
      { token: "-t", meaning: "Find a device matching a NAME=value token." },
      { token: "-U", meaning: "Find the device with a given filesystem UUID." },
      { token: "-n", meaning: "Restrict probing to selected filesystem types." },
      { token: "-w", meaning: "Choose where the cache is written." },
      { token: "-g", meaning: "Gather probing information without printing normal device output." },
    ],
    note: "blkid reads device metadata. Use findmnt to understand how a device is currently mounted.",
  },
  findfs: {
    purpose: "Find a block device by a filesystem label, UUID, or other tag.",
    syntax: "findfs LABEL=label|UUID=uuid|PARTUUID=uuid|PARTLABEL=label",
    parts: [],
    note: "findfs prints a device path and does not mount or modify it.",
  },
  fstrim: {
    purpose: "Discard unused blocks on a mounted filesystem, usually for SSD or thin-provisioned storage.",
    syntax: "fstrim [options] mountpoint",
    parts: [
      { token: "-a", meaning: "Trim all mounted filesystems that support it." },
      { token: "-A", meaning: "Trim filesystems listed in /etc/fstab." },
      { token: "-I", meaning: "Trim filesystems listed in selected files." },
      { token: "-o", meaning: "Start trimming at a byte offset." },
      { token: "-l", meaning: "Limit the number of bytes trimmed." },
      { token: "-m", meaning: "Trim only ranges at least this large." },
      { token: "-t", meaning: "Restrict trimming to selected filesystem types." },
      { token: "-v", meaning: "Report how many bytes were discarded." },
      { token: "-n", meaning: "Perform a dry run without discarding blocks." },
      { token: "--quiet", meaning: "Suppress normal output." },
      { token: "--quiet-unsupported", meaning: "Suppress errors when trim is unsupported." },
    ],
    note: "fstrim is a storage operation. Use the mountpoint you intend and check device or filesystem guidance before scheduling it frequently.",
  },
  fsck: {
    purpose: "Check and, when requested, repair filesystems.",
    syntax: "fsck [options] [filesystem]",
    parts: [
      { token: "-A", meaning: "Check filesystems listed in /etc/fstab." },
      { token: "-C", meaning: "Show a progress bar, optionally using a selected file descriptor." },
      { token: "-l", meaning: "Lock the device for exclusive checking." },
      { token: "-N", meaning: "Show what would be done without running the checker." },
      { token: "-M", meaning: "Skip mounted filesystems." },
      { token: "-P", meaning: "Check filesystems in parallel, including the root filesystem." },
      { token: "-R", meaning: "Skip the root filesystem when checking all entries." },
      { token: "-r", meaning: "Report statistics for each checked device." },
      { token: "-s", meaning: "Serialize filesystem checks instead of running them in parallel." },
      { token: "-T", meaning: "Do not print the tool name in the output." },
      { token: "-V", meaning: "Print each filesystem-specific command before running it." },
      { token: "-t", meaning: "Restrict checks to selected filesystem types." },
    ],
    note: "Never repair a mounted filesystem casually. Use -N for an initial dry run, then consult the filesystem-specific checker manual for repair flags.",
  },
  fdisk: {
    purpose: "Inspect and edit partition tables on block devices.",
    syntax: "fdisk [options] device",
    parts: [
      { token: "-l", meaning: "List partition tables without entering the editor." },
      { token: "-b", meaning: "Set the sector size." },
      { token: "-B", meaning: "Protect boot bits when creating a new partition label." },
      { token: "-c", meaning: "Choose DOS or non-DOS compatibility mode." },
      { token: "-L", meaning: "Choose when to use terminal colors." },
      { token: "-n", meaning: "Do not create a default partition table on an empty device." },
      { token: "-o", meaning: "Choose the columns shown in list output." },
      { token: "-t", meaning: "Recognize only a selected partition-table type." },
      { token: "-u", meaning: "Show sectors instead of cylinders in older output modes." },
      { token: "-w", meaning: "Choose when changes are written to the device." },
      { token: "-W", meaning: "Choose when changes are wiped from the device." },
      { token: "-x", meaning: "Use expert mode with additional partition controls." },
    ],
    note: "fdisk can make a disk unbootable or destroy access to data. Inspect with -l first and never guess the device path.",
  },
  partx: {
    purpose: "Tell the kernel about partitions on a block device and list or remove them from the kernel's view.",
    syntax: "partx [options] device",
    parts: [
      { token: "-a", meaning: "Add partitions to the kernel's partition table." },
      { token: "-d", meaning: "Delete partitions from the kernel's partition table." },
      { token: "-s", meaning: "Show partition sizes in sectors." },
      { token: "-u", meaning: "Update existing partition entries." },
      { token: "-g", meaning: "Hide headings in --show output." },
      { token: "-b", meaning: "Print sizes in bytes." },
      { token: "-n", meaning: "Select a range of partition numbers." },
      { token: "-o", meaning: "Choose the output columns." },
      { token: "-P", meaning: "Use a parsable table output format." },
      { token: "-r", meaning: "Use raw output." },
      { token: "-S", meaning: "Override the sector size." },
      { token: "-t", meaning: "Restrict output or operations to a partition type." },
      { token: "-v", meaning: "Print more details about the operation." },
    ],
    note: "partx changes the kernel's view of partitions and can affect mounts and applications using the device. Confirm the device and partition numbers first.",
  },
  udevadm: {
    purpose: "Query, monitor, test, and trigger Linux device-manager events.",
    syntax: "udevadm command [options]",
    parts: [
      { token: "info", meaning: "Query device properties, attributes, and symlinks." },
      { token: "monitor", meaning: "Listen for kernel and udev device events." },
      { token: "settle", meaning: "Wait until the current udev event queue is processed." },
      { token: "trigger", meaning: "Ask the kernel to replay device events." },
      { token: "test", meaning: "Simulate the udev rule processing for a device." },
      { token: "test-builtin", meaning: "Test one of udev's built-in rule commands." },
      { token: "control", meaning: "Change the running udev daemon's state." },
      { token: "verify", meaning: "Check the syntax and semantics of udev rules files." },
      { token: "wait", meaning: "Wait for a device or device symlink to be initialized." },
      { token: "-q", meaning: "Choose which property to query with udevadm info." },
      { token: "-p", meaning: "Select a device path." },
      { token: "-n", meaning: "Select a device node name." },
      { token: "-r", meaning: "Print absolute paths for device names or symlinks." },
      { token: "-e", meaning: "Print the complete property database when supported." },
      { token: "-s", meaning: "Filter events or attributes by subsystem." },
      { token: "-a", meaning: "Walk the device's sysfs attribute chain." },
      { token: "-t", meaning: "Display a sysfs tree." },
      { token: "-x", meaning: "Print properties as key/value pairs." },
      { token: "-P", meaning: "Prefix exported property names." },
      { token: "-d", meaning: "Print the major/minor device ID for a file." },
      { token: "--json", meaning: "Format supported udevadm output as JSON." },
    ],
    note: "udevadm trigger can cause devices and rules to be reprocessed. Prefer info, monitor, and test while investigating.",
  },
  swapon: {
    purpose: "Enable swap devices or files, or list active swap areas.",
    syntax: "swapon [options] [device|file]",
    parts: [
      { token: "-a", meaning: "Enable all swap entries from /etc/fstab." },
      { token: "-s", meaning: "Show a summary of active swap areas." },
      { token: "--show", meaning: "Print active swap areas in a structured table." },
      { token: "-p", meaning: "Set the swap priority." },
      { token: "-d", meaning: "Enable discard support for the swap area." },
      { token: "-f", meaning: "Reinitialize swap space when its page size needs fixing." },
      { token: "-e", meaning: "Skip unavailable swap entries when used with -a." },
      { token: "-o", meaning: "Set swap-specific options." },
      { token: "-T", meaning: "Use an alternate fstab file." },
      { token: "-L", meaning: "Select a swap area by filesystem label." },
      { token: "-U", meaning: "Select a swap area by UUID." },
      { token: "--raw", meaning: "Use raw output with --show." },
      { token: "--noheadings", meaning: "Hide headings in --show output." },
      { token: "--bytes", meaning: "Print swap sizes in bytes with --show." },
    ],
    note: "Enabling swap changes memory-management behavior and generally requires root. Review the device or file before activating it.",
  },
  swapoff: {
    purpose: "Disable an active swap device or file.",
    syntax: "swapoff [options] [device|file]",
    parts: [
      { token: "-a", meaning: "Disable all swap areas listed in /etc/fstab." },
      { token: "-v", meaning: "Print more details about each operation." },
      { token: "-L", meaning: "Select a swap area by filesystem label." },
      { token: "-U", meaning: "Select a swap area by UUID." },
    ],
    note: "The kernel must move used pages elsewhere. Disabling swap with too little free memory can fail or put pressure on the system.",
  },
  sync: {
    purpose: "Ask the kernel to flush pending filesystem data to storage.",
    syntax: "sync [options] [file]",
    parts: [
      { token: "-d", meaning: "Synchronize file data without all metadata when supported." },
      { token: "-f", meaning: "Synchronize the filesystem containing a file." },
    ],
    note: "sync asks the kernel to write pending data. It does not repair filesystem corruption or safely remove a device by itself.",
  },
} satisfies CommandCatalog;

