import type { CommandCatalog } from "../types";
export const kernelGuides = {
  lsmod: {
    purpose: "List kernel modules currently loaded into the running kernel.",
    syntax: "lsmod",
    parts: [],
    note: "lsmod reads /proc/modules. Use modinfo to inspect a module and modprobe to load one with dependency handling.",
  },
  modprobe: {
    purpose: "Load or remove a kernel module while resolving its dependencies.",
    syntax: "modprobe [options] module",
    parts: [
      { token: "-a", meaning: "Load every module named on the command line." },
      { token: "-b", meaning: "Use the module blacklist when resolving aliases." },
      { token: "-c", meaning: "Show the effective module configuration." },
      { token: "-C", meaning: "Use a chosen module configuration file." },
      { token: "-d", meaning: "Use a chosen directory as the module tree root." },
      { token: "-D", meaning: "Show the module dependencies without changing loaded modules." },
      { token: "-f", meaning: "Force module insertion or removal when supported. This is dangerous." },
      { token: "-i", meaning: "Ignore install or remove commands from module configuration." },
      { token: "-n", meaning: "Dry-run the operation without changing loaded modules." },
      { token: "-q", meaning: "Suppress error messages for missing modules." },
      { token: "-r", meaning: "Remove a module instead of loading it." },
      { token: "-R", meaning: "Resolve an alias without loading the resulting module." },
      { token: "-S", meaning: "Use a selected kernel release instead of the running release." },
      { token: "-s", meaning: "Send messages to the system log." },
      { token: "-v", meaning: "Print more details about the operation." },
      { token: "-w", meaning: "Wait for a module to become unused before removing it." },
      { token: "--show-depends", meaning: "Print the modules that would be loaded as dependencies." },
      { token: "--first-time", meaning: "Fail if the requested module is already loaded." },
      { token: "--force-vermagic", meaning: "Ignore a kernel version mismatch. This can destabilize the system." },
    ],
    note: "Use modprobe rather than insmod when possible because it understands aliases, configuration, and dependencies. Loading or removing modules normally needs root.",
  },
  modinfo: {
    purpose: "Display metadata, parameters, aliases, and dependencies for a kernel module.",
    syntax: "modinfo [options] module",
    parts: [
      { token: "-F", meaning: "Print only one named metadata field." },
      { token: "-k", meaning: "Inspect modules for a specific kernel release." },
      { token: "-n", meaning: "Print the module filename only." },
      { token: "-0", meaning: "Separate fields with NUL bytes for scripts." },
      { token: "-a", meaning: "Show the module author field." },
      { token: "-d", meaning: "Show the module description field." },
      { token: "-l", meaning: "Show the module license field." },
      { token: "-m", meaning: "Treat the argument as a module name rather than an alias or filename." },
      { token: "-p", meaning: "Show parameters accepted by the module." },
      { token: "-b", meaning: "Use a different module tree as the search base." },
    ],
    note: "modinfo inspects module files; it does not load the module.",
  },
  depmod: {
    purpose: "Generate the dependency and alias files used by the kernel module loader.",
    syntax: "depmod [options] [kernel-release]",
    parts: [
      { token: "-a", meaning: "Process all modules for the selected kernel release." },
      { token: "-A", meaning: "Update only when a module is newer than the existing dependency file." },
      { token: "-b", meaning: "Use a different directory as the module-tree root." },
      { token: "-e", meaning: "Report unresolved symbols." },
      { token: "-F", meaning: "Use a System.map file when checking unresolved symbols." },
      { token: "-C", meaning: "Read module configuration from a chosen path." },
      { token: "-n", meaning: "Print the generated dependency data instead of writing it." },
      { token: "-v", meaning: "Print each processed module." },
      { token: "-w", meaning: "Warn about duplicate module files." },
    ],
    note: "Package managers normally run depmod for you. It updates module metadata, not the kernel image itself.",
  },
  insmod: {
    purpose: "Insert one kernel module file into the running kernel.",
    syntax: "insmod [options] module-file [module-parameters]",
    parts: [
      { token: "-f", meaning: "Force insertion despite a version mismatch when supported." },
      { token: "-s", meaning: "Send messages to the system log instead of the terminal." },
      { token: "-v", meaning: "Print more details about the operation." },
      { token: "-V", meaning: "Print the tool version." },
    ],
    note: "insmod does not resolve dependencies. Prefer modprobe for normal module loading, and treat insertion as a root-level system change.",
  },
  rmmod: {
    purpose: "Remove one or more kernel modules from the running kernel.",
    syntax: "rmmod [options] module",
    parts: [
      { token: "-f", meaning: "Force removal when the kernel was built to allow it." },
      { token: "-s", meaning: "Send messages to the system log." },
      { token: "-v", meaning: "Print more details about the operation." },
      { token: "-w", meaning: "Wait for the module to become unused before removing it." },
    ],
    note: "Removing a module can disconnect hardware or break services that depend on it. Check lsmod and the module dependencies first.",
  },
} satisfies CommandCatalog;

