import type { CommandCatalog } from "../types";
export const networkGuides = {
  ip: {
    purpose: "Inspect and configure network interfaces, addresses, routes, and neighbors.",
    syntax: "ip [options] object command",
    parts: [
      { token: "-br", meaning: "Use a short human-readable summary format." },
      { token: "-c", meaning: "Use color in terminal output." },
      { token: "-j", meaning: "Print output as JSON." },
      { token: "-4", meaning: "Limit the operation to IPv4." },
      { token: "-6", meaning: "Limit the operation to IPv6." },
      { token: "addr", meaning: "Work with interface addresses." },
      { token: "route", meaning: "Work with the routing table." },
    ],
    note: "ip can be read-only or change live networking. Commands such as ip addr add and ip route change are privileged.",
  },
  ping: {
    purpose: "Send network probes and report whether a host responds.",
    syntax: "ping [options] host",
    parts: [
      { token: "-c", meaning: "Stop after sending this many probes." },
      { token: "-i", meaning: "Wait this many seconds between probes." },
      { token: "-W", meaning: "Wait this many seconds for each reply." },
      { token: "-4", meaning: "Use IPv4 only." },
      { token: "-6", meaning: "Use IPv6 only." },
      { token: "-s", meaning: "Choose the size of the probe payload." },
    ],
    note: "A failed ping does not prove that a host is down. Firewalls and routers can block ICMP.",
  },
  ss: {
    purpose: "Inspect sockets and current network connections.",
    syntax: "ss [options]",
    parts: [
      { token: "-t", meaning: "Show TCP sockets." },
      { token: "-u", meaning: "Show UDP sockets." },
      { token: "-l", meaning: "Show listening sockets." },
      { token: "-n", meaning: "Show numeric addresses and ports without DNS lookups." },
      { token: "-p", meaning: "Show the process using each socket." },
      { token: "-a", meaning: "Show listening and non-listening sockets." },
    ],
    note: "ss is the usual modern replacement for netstat. It observes connections and does not open them.",
  },
  curl: {
    purpose: "Transfer data to or from a URL using protocols such as HTTP and HTTPS.",
    syntax: "curl [options] URL",
    parts: [
      { token: "-I", meaning: "Fetch response headers without the response body." },
      { token: "-L", meaning: "Follow HTTP redirects." },
      { token: "-O", meaning: "Save the response using the remote filename." },
      { token: "-o", meaning: "Save the response to a chosen filename." },
      { token: "-s", meaning: "Use silent mode without progress and error messages." },
      { token: "-f", meaning: "Fail with an error status for HTTP error responses." },
      { token: "-X", meaning: "Choose the HTTP method explicitly." },
      { token: "-d", meaning: "Send request data, commonly for a POST request." },
      { token: "-H", meaning: "Add a request header." },
    ],
    note: "curl downloads or sends data. Never pipe an unfamiliar curl response directly into a shell without inspecting it.",
  },
  wget: {
    purpose: "Download files and web resources from URLs.",
    syntax: "wget [options] URL",
    parts: [
      { token: "-O", meaning: "Write the response to a chosen file." },
      { token: "-q", meaning: "Use quiet output." },
      { token: "-c", meaning: "Resume a partial download when the server supports it." },
      { token: "-r", meaning: "Download recursively from links." },
      { token: "-P", meaning: "Choose the destination directory." },
      { token: "--spider", meaning: "Check a URL without downloading its contents." },
    ],
    note: "wget writes downloaded content to disk. Check the URL and destination before using recursive options.",
  },
  ssh: {
    purpose: "Open an encrypted shell session or run a command on another machine.",
    syntax: "ssh [options] user@host [command]",
    parts: [
      { token: "-p", meaning: "Connect to a chosen remote port." },
      { token: "-i", meaning: "Use a chosen private key file." },
      { token: "-L", meaning: "Forward a local port through the SSH connection." },
      { token: "-R", meaning: "Forward a remote port back through the SSH connection." },
      { token: "-N", meaning: "Do not run a remote command, useful for port forwarding." },
      { token: "-T", meaning: "Disable pseudo-terminal allocation." },
      { token: "-v", meaning: "Print verbose connection diagnostics." },
    ],
    note: "ssh can run remote commands with your remote account's permissions. Read the full command before pressing Enter.",
  },
  scp: {
    purpose: "Copy files between local and remote machines over SSH.",
    syntax: "scp [options] source user@host:destination",
    parts: [
      { token: "-r", meaning: "Copy directories recursively." },
      { token: "-P", meaning: "Use a chosen remote SSH port." },
      { token: "-i", meaning: "Use a chosen private key file." },
      { token: "-p", meaning: "Preserve file times and modes." },
      { token: "-q", meaning: "Suppress progress and warning messages." },
    ],
    note: "The direction is determined by which side contains user@host. Check it before copying a directory tree.",
  },
} satisfies CommandCatalog;

