import type { CommandCatalog } from "../types";
export const processesGuides = {
  ps: {
    purpose: "Show a point-in-time list of running processes.",
    syntax: "ps",
    parts: [
      { token: "PID", meaning: "The process identifier used by commands such as kill." },
      { token: "CMD", meaning: "The command that started the process." },
    ],
    note: "Read the PID and command together before sending a signal.",
  },
  top: {
    purpose: "View process activity in a continuously updating interface.",
    syntax: "top -n 1",
    parts: [
      { token: "-n 1", meaning: "Take one update and exit instead of looping forever." },
    ],
    note: "The exercise uses one snapshot so the browser shell stays predictable.",
  },
  kill: {
    purpose: "Send a signal to a process identified by its PID.",
    syntax: "kill PID",
    parts: [
      { token: "TERM", meaning: "The default request asks a process to stop cleanly." },
      { token: "-9", meaning: "Force termination in a real system. Use it only when gentler signals fail." },
    ],
    note: "A PID can be reused. Confirm the process before sending a signal on a real machine.",
  },
  pgrep: {
    purpose: "Find process IDs whose command lines match a pattern.",
    syntax: "pgrep [options] pattern",
    parts: [
      { token: "-a", meaning: "Print the full command line with each process ID." },
      { token: "-f", meaning: "Match the complete command line instead of only the executable name." },
      { token: "-u", meaning: "Match processes owned by a user." },
      { token: "-x", meaning: "Require the complete name to match." },
      { token: "-n", meaning: "Select the newest matching process." },
      { token: "-o", meaning: "Select the oldest matching process." },
    ],
    note: "pgrep only finds processes. Verify the command line before sending a signal with kill or pkill.",
  },
  pkill: {
    purpose: "Send a signal to processes whose command lines match a pattern.",
    syntax: "pkill [options] pattern",
    parts: [
      { token: "-f", meaning: "Match the complete command line." },
      { token: "-u", meaning: "Match processes owned by a user." },
      { token: "-e", meaning: "Print the name of each process that receives a signal." },
      { token: "-TERM", meaning: "Send a named signal such as TERM instead of the default." },
    ],
    note: "pkill can stop multiple processes at once. Use pgrep first to inspect the exact matches.",
  },
  nice: {
    purpose: "Run a command with a chosen CPU scheduling niceness.",
    syntax: "nice [option] command",
    parts: [
      { token: "-n", meaning: "Add a niceness adjustment to the command's priority." },
    ],
    note: "A higher niceness usually gives a process less scheduling priority. Lowering niceness may require root.",
  },
  nohup: {
    purpose: "Run a command so it can keep running after the terminal closes.",
    syntax: "nohup command [argument]",
    parts: [],
    note: "nohup redirects output to nohup.out when needed. It does not create a service or monitor the process.",
  },
  timeout: {
    purpose: "Run a command for a limited time and send it a signal when the limit expires.",
    syntax: "timeout [options] duration command",
    parts: [
      { token: "-s", meaning: "Choose the signal sent when the duration expires." },
      { token: "-k", meaning: "Send a second kill signal after an additional grace period." },
      { token: "--preserve-status", meaning: "Return the command's status instead of timeout's status." },
    ],
    note: "timeout limits waiting. It does not guarantee that a command exits cleanly when the signal is ignored.",
  },
  su: {
    purpose: "Start a shell or command as another user.",
    syntax: "su [options] [user]",
    parts: [
      { token: "-", meaning: "Start a login shell with the target user's environment." },
      { token: "-c", meaning: "Run one command instead of opening an interactive shell." },
      { token: "-s", meaning: "Choose the shell to run." },
      { token: "-l", meaning: "Start a login shell." },
    ],
    note: "su changes identity for the new process. Check whether the command will write files as the target user.",
  },
  passwd: {
    purpose: "Change or manage a user's password and password status.",
    syntax: "passwd [options] [user]",
    parts: [
      { token: "-l", meaning: "Lock the password so it cannot be used for authentication." },
      { token: "-u", meaning: "Unlock a previously locked password." },
      { token: "-d", meaning: "Delete the password, which can weaken account security." },
      { token: "-e", meaning: "Expire the password and require a change at next login." },
      { token: "-S", meaning: "Show the password status." },
    ],
    note: "Changing another user's password normally needs administrator privileges. Treat -d and account locks as security changes.",
  },
  chrt: {
    purpose: "Read or change a process's scheduling policy and real-time priority.",
    syntax: "chrt [options] priority command [argument...]",
    parts: [
      { token: "-a", meaning: "Operate on all threads of the selected process." },
      { token: "-m", meaning: "Show the available scheduling policies." },
      { token: "-p", meaning: "Inspect or change an existing process instead of launching a command." },
      { token: "-v", meaning: "Print the selected policy and priority." },
      { token: "-b", meaning: "Use the SCHED_BATCH policy." },
      { token: "-o", meaning: "Use the normal SCHED_OTHER policy." },
      { token: "-f", meaning: "Use the first-in-first-out real-time policy." },
      { token: "-r", meaning: "Use the round-robin real-time policy." },
      { token: "-d", meaning: "Use the deadline scheduling policy." },
      { token: "-i", meaning: "Use the idle scheduling policy." },
      { token: "-e", meaning: "Use the SCHED_EXT policy when the kernel provides it." },
      { token: "-R", meaning: "Set the reset-on-fork scheduling flag." },
      { token: "-T", meaning: "Set the runtime parameter for deadline scheduling." },
      { token: "-P", meaning: "Set the period parameter for deadline scheduling." },
      { token: "-D", meaning: "Set the deadline parameter for deadline scheduling." },
    ],
    note: "Real-time scheduling can starve other work. Changing another process usually requires CAP_SYS_NICE or root.",
  },
  taskset: {
    purpose: "Read or set the CPU affinity mask of a process or command.",
    syntax: "taskset [options] mask|cpu-list command [argument...]",
    parts: [
      { token: "-p", meaning: "Operate on an existing process ID." },
      { token: "-c", meaning: "Use a list of CPU numbers instead of a hexadecimal mask." },
      { token: "-a", meaning: "Apply the operation to all threads of the process." },
    ],
    note: "Affinity changes can make a program slower or prevent it from using available CPUs. Confirm the process and CPU list first.",
  },
  prlimit: {
    purpose: "Read or change the resource limits attached to a process.",
    syntax: "prlimit [options] [--resource[=limit]] [command [argument...]]",
    parts: [
      { token: "-p", meaning: "Inspect or change the limits of this process ID." },
      { token: "-o", meaning: "Choose the output columns." },
      { token: "--raw", meaning: "Use raw output without display formatting." },
      { token: "--noheadings", meaning: "Hide the output headings." },
      { token: "--nofile", meaning: "Set the maximum number of open file descriptors." },
      { token: "--stack", meaning: "Set the maximum process stack size." },
      { token: "--as", meaning: "Set the maximum address-space size." },
      { token: "--cpu", meaning: "Set the maximum CPU time." },
      { token: "--nproc", meaning: "Set the maximum number of processes for the user." },
      { token: "--memlock", meaning: "Set the maximum amount of memory that may be locked." },
      { token: "--core", meaning: "Set the maximum size of core dump files." },
      { token: "--data", meaning: "Set the maximum process data-segment size." },
      { token: "--nice", meaning: "Set the maximum nice priority the process may raise to." },
      { token: "--fsize", meaning: "Set the maximum size of files the process may write." },
      { token: "--sigpending", meaning: "Set the maximum number of pending signals." },
      { token: "--rss", meaning: "Set the maximum resident-set size." },
      { token: "--msgqueue", meaning: "Set the maximum POSIX message-queue bytes." },
      { token: "--rtprio", meaning: "Set the maximum real-time scheduling priority." },
      { token: "--rttime", meaning: "Set the CPU-time limit for real-time scheduling." },
      { token: "--locks", meaning: "Set the maximum number of file locks." },
    ],
    note: "A limit can make a service fail in surprising ways. Use prlimit without a new value to inspect before changing anything.",
  },
  setpriv: {
    purpose: "Run a program with selected user IDs, groups, capabilities, or privilege restrictions.",
    syntax: "setpriv [options] program [argument...]",
    parts: [
      { token: "--no-new-privs", meaning: "Prevent the program and its children from gaining new privileges." },
      { token: "--nnp", meaning: "Short alias for --no-new-privs." },
      { token: "--reuid", meaning: "Run with a selected real and effective user ID." },
      { token: "--regid", meaning: "Run with a selected real and effective group ID." },
      { token: "--ruid", meaning: "Set the real user ID." },
      { token: "--euid", meaning: "Set the effective user ID." },
      { token: "--rgid", meaning: "Set the real group ID." },
      { token: "--egid", meaning: "Set the effective group ID." },
      { token: "--clear-groups", meaning: "Discard supplementary groups." },
      { token: "--keep-groups", meaning: "Keep supplementary groups instead of clearing them." },
      { token: "--init-groups", meaning: "Initialize supplementary groups for the selected user." },
      { token: "--groups", meaning: "Set supplementary groups explicitly." },
      { token: "--inh-caps", meaning: "Set the inheritable capability set." },
      { token: "--ambient-caps", meaning: "Set capabilities preserved across execve." },
      { token: "--bounding-set", meaning: "Change the capabilities the process may ever gain." },
      { token: "--keep-caps", meaning: "Keep capabilities across a user-ID change." },
      { token: "--securebits", meaning: "Set securebits controlling privilege transitions." },
      { token: "--pdeathsig", meaning: "Set or clear the signal delivered when the parent dies." },
      { token: "--ptracer", meaning: "Control which process may ptrace the child." },
      { token: "--list-caps", meaning: "List capability names understood by the tool." },
      { token: "--reset-env", meaning: "Clear the environment and initialize a small safe set." },
      { token: "--dump", meaning: "Print the current privilege state instead of launching a program." },
    ],
    note: "setpriv changes the security context of the child process. A wrong UID, group, or capability set can make a program unsafe or unusable.",
  },
  renice: {
    purpose: "Change the nice value, and therefore scheduling priority, of running processes.",
    syntax: "renice [options] priority [-p pid] [-g pgrp] [-u user]",
    parts: [
      { token: "-n", meaning: "Set the new nice value." },
      { token: "-p", meaning: "Interpret following identifiers as process IDs." },
      { token: "-g", meaning: "Interpret following identifiers as process-group IDs." },
      { token: "-u", meaning: "Interpret following identifiers as usernames." },
      { token: "--priority", meaning: "Set an absolute nice value." },
      { token: "--relative", meaning: "Adjust the current nice value by a relative amount." },
    ],
    note: "A higher nice value gives a process less scheduling priority. Lowering it generally requires extra privilege.",
  },
  ionice: {
    purpose: "Read or change a process's I/O scheduling class and priority.",
    syntax: "ionice [options] [command [argument...]]",
    parts: [
      { token: "-c", meaning: "Choose the I/O scheduling class." },
      { token: "-n", meaning: "Choose the priority within a class that supports it." },
      { token: "-p", meaning: "Operate on an existing process ID." },
      { token: "-P", meaning: "Operate on processes in a process group." },
      { token: "-t", meaning: "Ignore failures when setting a process priority." },
      { token: "-u", meaning: "Operate on processes owned by selected users." },
    ],
    note: "ionice affects how storage work competes with other I/O. Check the process ID before changing a running service.",
  },
  lsns: {
    purpose: "List Linux namespaces and the processes that own them.",
    syntax: "lsns [options] [namespace-type]",
    parts: [
      { token: "-a", meaning: "List all namespaces, including those without a visible process." },
      { token: "-J", meaning: "Print JSON output." },
      { token: "-l", meaning: "Use a list-style output format." },
      { token: "-n", meaning: "Hide the column headings." },
      { token: "-o", meaning: "Choose the output columns." },
      { token: "-P", meaning: "Include persistent namespaces without a visible process." },
      { token: "-p", meaning: "Show only namespaces used by a process ID." },
      { token: "-r", meaning: "Use raw output." },
      { token: "-t", meaning: "Filter by namespace type, such as net or pid." },
      { token: "-T", meaning: "Display namespaces as a tree." },
      { token: "-u", meaning: "Do not truncate text in columns." },
      { token: "-W", meaning: "Do not wrap multi-line values." },
    ],
    note: "Namespaces isolate process views of resources such as PIDs, mounts, users, and networks. lsns only inspects them.",
  },
  nsenter: {
    purpose: "Run a program inside the namespaces of another process.",
    syntax: "nsenter [options] [program [argument...]]",
    parts: [
      { token: "-t", meaning: "Target the namespaces associated with this process ID." },
      { token: "-a", meaning: "Enter all supported namespaces of the target." },
      { token: "-m", meaning: "Enter the target's mount namespace." },
      { token: "-u", meaning: "Enter the target's UTS hostname/domain namespace." },
      { token: "-i", meaning: "Enter the target's IPC namespace." },
      { token: "-n", meaning: "Enter the target's network namespace." },
      { token: "-p", meaning: "Enter the target's PID namespace." },
      { token: "-U", meaning: "Enter the target's user namespace." },
      { token: "-C", meaning: "Enter the target's cgroup namespace." },
      { token: "-T", meaning: "Enter the target's time namespace." },
      { token: "-S", meaning: "Set the user ID inside the entered namespace." },
      { token: "-G", meaning: "Set the group ID inside the entered namespace." },
      { token: "-r", meaning: "Set the root directory inside the entered namespace." },
      { token: "-w", meaning: "Set the working directory inside the entered namespace." },
      { token: "-e", meaning: "Inherit environment variables from the target process." },
      { token: "-F", meaning: "Do not fork before running the program." },
      { token: "--no-fork", meaning: "Long form of -F: do not fork before running the program." },
    ],
    note: "nsenter can make a shell see another process's mounts, network, or process tree. Check the target PID and command carefully.",
  },
  unshare: {
    purpose: "Run a program in newly created Linux namespaces.",
    syntax: "unshare [options] [program [argument...]]",
    parts: [
      { token: "-m", meaning: "Create a new mount namespace." },
      { token: "-u", meaning: "Create a new UTS hostname/domain namespace." },
      { token: "-i", meaning: "Create a new IPC namespace." },
      { token: "-n", meaning: "Create a new network namespace." },
      { token: "-p", meaning: "Create a new PID namespace." },
      { token: "-U", meaning: "Create a new user namespace." },
      { token: "-C", meaning: "Create a new cgroup namespace." },
      { token: "-f", meaning: "Fork before launching the program." },
      { token: "-R", meaning: "Run the command with a selected root directory." },
      { token: "-w", meaning: "Run the command from a selected working directory." },
      { token: "-S", meaning: "Set the user ID in the new user namespace." },
      { token: "-G", meaning: "Set the group ID in the new user namespace." },
      { token: "-r", meaning: "Map the current user to root in the new user namespace." },
      { token: "-c", meaning: "Map the current user to itself in the new user namespace." },
      { token: "--mount-proc", meaning: "Mount a proc filesystem for the new PID namespace." },
      { token: "--map-auto", meaning: "Automatically map subordinate user and group IDs." },
      { token: "--map-root-user", meaning: "Map the current user to root inside a new user namespace." },
      { token: "--keep-caps", meaning: "Keep capabilities across a user-namespace change." },
      { token: "--kill-child", meaning: "Kill the child process when unshare exits." },
    ],
    note: "Namespaces are powerful isolation primitives, not a complete security boundary by themselves. Start with a disposable environment.",
  },
} satisfies CommandCatalog;

